vlans:
- id: 70
  name: Server
- id: 80
  name: Jail
- id: 100
  name: Infra
- id: 178
  name: User
pings:
- host: 192.168.70.1
  name: Server VLAN Gateway
- host: 192.168.80.1
  name: Jail VLAN Gateway
- host: 172.16.100.1
  name: Infra VLAN Gateway

- host: 8.8.8.8
  name: Google DNS
wifi:
  interface: wlan0
  update_interval: 5
